---
title: "WK2"
output: html_document
date: "2022-12-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(plotly)
library(RColorBrewer)
library(classInt)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(geojsonio)
library(maptools)
```

```{r}
Data1 <- c(1:100)
Data2 <- c(101:200)

plot(Data1, Data2, col="red")

Data3 <- rnorm(100, mean = 53, sd=34)
Data4 <- rnorm(100, mean = 64, sd=14)

plot(Data3, Data4, col="blue")

?plot

df <- data.frame(Data1, Data2)
plot(df, col="green")

df[1:10, 1]
df[5:15,]
df[c(2,3,6),2]
df[,1]

df <- df %>%
  dplyr::rename(column1 = Data1, column2=Data2)

df$column1
```

```{r}
LondonDataOSK <- read.csv('D:/UCL_CODE/CASA0005/data/WK2/LondonData.csv', 
                         header = TRUE, 
                         sep = ',',  
                         encoding = 'latin1')

LondonData <- read_csv('https://data.london.gov.uk/download/ward-profiles-and-atlas/772d2d64-e8c6-46cb-86f9-e52b4c7851bc/ward-profiles-excel-version.csv',
                       locale = locale(encoding = 'latin1'),
                       na = 'n/a')

class(LondonData)
class(LondonDataOSK)

Datatypelist <- LondonData %>% 
  summarise_all(class) %>%
  pivot_longer(everything())

Datatypelist

LondonBoroughs <- LondonData[626:658,]

Femalelifeexp<- LondonData %>% 
  filter(`Female life expectancy -2009-13`>90)

LondonBoroughs<- LondonData %>% 
  filter(str_detect(`New code`, "^E09"))

LondonBoroughs$`Ward name`

LondonBoroughs<-LondonBoroughs %>%
  distinct()

LondonBoroughs_contains<-LondonBoroughs %>% 
  dplyr::select(contains("expectancy"), 
         contains("obese - 2011/12 to 2013/14"),
         contains("Ward name")) 

LondonBoroughs <- LondonBoroughs %>%
  dplyr::rename(Borough=`Ward name`)%>%
  clean_names()

head(LondonBoroughs)

Life_expectancy <- LondonBoroughs %>% 
  #new column with average of male and female life expectancy
  mutate(averagelifeexpectancy= (female_life_expectancy_2009_13 +
                                    male_life_expectancy_2009_13)/2)%>%
  #new column with normalised life expectancy
  mutate(normalisedlifeepectancy= averagelifeexpectancy /
           mean(averagelifeexpectancy))%>%
  #select only columns we want
  dplyr::select(new_code,
         borough,
         averagelifeexpectancy, 
         normalisedlifeepectancy)%>%
  #arrange in descending order
  #ascending is the default and would be
  #arrange(normalisedlifeepectancy)
  arrange(desc(normalisedlifeepectancy))

slice_head(Life_expectancy, n=5)

Life_expectancy2 <- Life_expectancy %>%
  mutate(UKcompare = case_when(averagelifeexpectancy>81.16 ~ "above UK average",
                               TRUE ~ "below UK average"))
Life_expectancy2

Life_expectancy2_group <- Life_expectancy2 %>%
  mutate(UKdiff = averagelifeexpectancy-81.16) %>%
  group_by(UKcompare)%>%
  summarise(range=max(UKdiff)-min(UKdiff), count=n(), Average=mean(UKdiff))

Life_expectancy2_group

Life_expectancy3 <- Life_expectancy %>%
  mutate(UKdiff = averagelifeexpectancy-81.16)%>%
  mutate(across(where(is.numeric), round, 3))%>%
  mutate(across(UKdiff, round, 0))%>%
  mutate(UKcompare = case_when(averagelifeexpectancy >= 81 ~ 
                                 str_c("equal or above UK average by",
                                       UKdiff, 
                                       "years", 
                                       sep=" "), 
                               TRUE ~ str_c("below UK average by",
                                            UKdiff,
                                            "years",
                                            sep=" ")))%>%
  group_by(UKcompare)%>%
  summarise(count=n())

Life_expectancy3

Life_expectancy4 <- Life_expectancy %>%
  mutate(UKdiff = averagelifeexpectancy-81.16)%>%
  mutate(across(where(is.numeric), round, 3))%>%
  mutate(across(UKdiff, round, 0))

Life_expectancy4

plot(LondonBoroughs$male_life_expectancy_2009_13,
     LondonBoroughs$percent_children_in_reception_year_who_are_obese_2011_12_to_2013_14)

plot_ly(LondonBoroughs, 
        #data for x axis
        x = ~male_life_expectancy_2009_13, 
        #data for y axis
        y = ~percent_children_in_reception_year_who_are_obese_2011_12_to_2013_14, 
        #attribute to display when hovering 
        text = ~borough, 
        type = "scatter", 
        mode = "markers")
```

```{r}
EW <- st_read("D:/UCL_CODE/CASA0005/data/WK2/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")

LondonMap <- EW
qtm(LondonMap)

LondonData <- clean_names(LondonData)

BoroughDataMap <- EW %>%
  # the . here just means use the data already loaded
  merge(.,
        LondonData, 
        by.x="GSS_CODE", 
        by.y="new_code",
        no.dups = TRUE)

tmap_mode("plot")
qtm(BoroughDataMap, 
    fill = "rate_of_job_seekers_allowance_jsa_claimants_2015")

tmaplondon <- BoroughDataMap %>%
  st_bbox(.) %>% 
  tmaptools::read_osm(., type = "osm", zoom = NULL)

tmap_mode("plot")

tm_shape(tmaplondon)+
tm_rgb()+
tm_shape(BoroughDataMap) + 
tm_polygons("rate_of_job_seekers_allowance_jsa_claimants_2015", 
        style="jenks",
        palette="YlOrBr",
        midpoint=NA,
        title="Rate per 1,000 people",
        alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Job seekers' Allowance Claimants", legend.position = c("right", "bottom"))

palette_explorer()

flytipping <- read_csv("https://data.london.gov.uk/download/fly-tipping-incidents/536278ff-a391-4f20-bc79-9e705c9b3ec0/fly-tipping-borough.csv")

flytipping1 <- read_csv("https://data.london.gov.uk/download/fly-tipping-incidents/536278ff-a391-4f20-bc79-9e705c9b3ec0/fly-tipping-borough.csv", 
                       col_types = cols(
                         code = col_character(),
                         area = col_character(),
                         year = col_character(),
                         total_incidents = col_number(),
                         total_action_taken = col_number(),
                         warning_letters = col_number(),
                         fixed_penalty_notices = col_number(),
                         statutory_notices = col_number(),
                         formal_cautions = col_number(),
                         injunctions = col_number(),
                         prosecutions = col_number()
                       ))
# view the data
view(flytipping1)

flytipping_long <- flytipping1 %>% 
  pivot_longer(
  cols = 4:11,
  names_to = "tipping_type",
  values_to = "count"
)

# view the data
view(flytipping_long)

flytipping2 <- flytipping1[,1:4]

flytipping_wide <- flytipping_long %>% 
  pivot_wider(
  id_cols = 1:2,
  names_from = c(year,tipping_type),
  names_sep = "_",
  values_from = count
)

view(flytipping_wide)

widefly <- flytipping2 %>% 
  pivot_wider(
  names_from = year, 
  values_from = total_incidents)

LondonBoroughs_new <- LondonBoroughs %>%
  # the . here just means use the data already loaded
  merge(.,
        widefly, 
        by.x="new_code", 
        by.y="code",
        no.dups = TRUE)
```

```{r}
#You need calcuate the average percent of science students (in all) grades per county meeting the required standards  计算 (每个县)（所有理科学生）(达到标准的)成绩平均比例
#and produce a map to show where the Country averages are above or below the State of Washington average.

student_grade <- read.csv('D:/UCL_CODE/CASA0005/data/WK2/Report_Card_Assessment_Data_2018-19_School_Year.csv')
washington <- st_read('D:/UCL_CODE/CASA0005/data/WK2/Washington_Counties_with_Natural_Shoreline___washsh_area.geojson')

student1 <- student_grade %>% 
  clean_names()
  
student2 <- student1 %>%
  filter(student_group_type == 'All') %>%
  filter(test_subject == 'Science') %>%
  filter(grade_level == 'All Grades')

student2$percent_met_tested_only <- student2$percent_met_tested_only %>%
  as.numeric()

student3 <- student2 %>%
  drop_na(percent_met_tested_only)

student4 <- student3 %>%
  group_by(county) %>%
  summarise(average = mean(percent_met_tested_only))

all_mean <- mean(student3$percent_met_tested_only)

student4 <- student4 %>%
  mutate(compare = case_when(average>all_mean ~ "above average",
                               TRUE ~ "below average"))

washington$COUNTY <- tolower(washington$COUNTY)
student4$county <- tolower(student4$county)

washington_compare <- washington %>%
  merge(.,
        student4,
        by.x = "COUNTY",
        by.y = "county",
        no.dups = TRUE
        )

qtm(washington_compare, fill="compare")
```