---
title: "WK6"
author: "Xianlai Yin"
date: "2022-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)
library(stringr)
library(tidyverse)
library(raster)
library(fpc)
library(dbscan)
library(plyr)
library(OpenStreetMap)
```

```{r data preparation}
LondonBoroughs <- st_read("D:/UCL_CODE/CASA0005/data/WK6/statistical-gis-boundaries-london/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp") %>%
  st_transform(.,27700)
BluePlaques <- st_read("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson") %>%
  st_transform(.,27700)

BoroughMap <- LondonBoroughs %>%
  dplyr::filter(str_detect(GSS_CODE, "^E09"))%>%
  st_transform(., 27700)

qtm(BoroughMap)
summary(BoroughMap)
summary(BluePlaques)

#plot the blue plaques in the city
tmap_mode("plot")
tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaques) +
  tm_dots(col = "blue")

BluePlaques <- distinct(BluePlaques)

BluePlaquesSub <- BluePlaques[BoroughMap,]
#check to see that they've been removed
tmap_mode("plot")
tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")

intersect_indices <- st_intersects(BoroughMap, BluePlaques)

OSM <- st_read("D:/UCL_CODE/CASA0005/data/WK6/greater-london-latest-free.shp/gis_osm_pois_a_free_1.shp") %>%
  st_transform(., 27700) %>%
  filter(fclass == 'hotel')
Londonborough <- st_read("D:/UCL_CODE/CASA0005/data/WK6/statistical-gis-boundaries-london/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp") %>%
  st_transform(.,27700)
Airbnb <- read_csv("D:/UCL_CODE/CASA0005/data/WK6/listings.csv") %>%
  st_as_sf(.,coords = c("longitude","latitude"), crs = 4326) %>%
  st_transform(., 27700) %>%
  filter(room_type == "Entire home/apt" & availability_365 == "365")

joinfun <- function(data1,data2){
output <- data1 %>%
  st_join(Londonborough,.) %>%
  add_count(GSS_CODE, name = "hotels_in_borough")
  return(output)
}

Hotels <- joinfun(OSM, Londonborough)
Airbnb <- joinfun(Airbnb, Londonborough)

Hotels <- Hotels %>%
  group_by(.,GSS_CODE,NAME) %>%
  summarise("Accomodation count" = unique(hotels_in_borough))

Airbnb <- Airbnb %>%
  group_by(.,GSS_CODE,NAME) %>%
  summarise("Accomodation count" = unique(hotels_in_borough))

all_accomodation <- st_join(Hotels, Airbnb,join = st_equals)
head(all_accomodation)

Harrow <- BoroughMap %>%
  filter(.,NAME == "Harrow")

qtm(Harrow)

BluePlaquesSub <- BluePlaques[Harrow,]

tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaqueSub) +
  tm_dots(col = "blue")
```

```{r Analysis}
BluePlaques <- st_read("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson") %>%
  st_transform(.,27700)
BluePlaques <- distinct(BluePlaques)
BluePlaquesSub <- BluePlaques[Harrow,]

window <- as.owin(Harrow)

BluePlaquesSub <- BluePlaquesSub %>%
  as(.,'Spatial')

BluePlaquesSub.ppp <- ppp(x = BluePlaquesSub@coords[,1],
                          y = BluePlaquesSub@coords[,2],
                          window = window)

BluePlaquesSub.ppp %>%
  plot(.,pch = 16, cex =0.5,main = "Blue Plaques Harrow")

BluePlaquesSub.ppp %>%
  density(.,sigma = 500) %>%
  plot()

BluePlaquesSub.ppp %>%
  density(.,sigma = 1000) %>%
  plot()

BluePlaquesSub.ppp %>%
  plot(.,pch = 16, cex =0.5,main = "Blue Plaques Harrow")

BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6,ny = 6) %>%
    plot(.,add = T,col = "red")

#计算是否是泊松分布
Qcount <- BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6,ny = 6) %>%
  as.data.frame() %>%
  dplyr::count(Var1=Freq) %>%
  dplyr::rename(Freqquadratcount = n)

Qcount %>%
  summarise_all(class)

sums <- Qcount %>%
  mutate(total =Var1 * Freqquadratcount) %>%
  dplyr::summarise(across(everything(),sum)) %>%
  dplyr::select(-Var1)
  
lambda <- Qcount %>%
  mutate(total = Var1 * Freqquadratcount) %>%
  dplyr::summarise(across(everything(),sum)) %>%
  dplyr::summarise(lambda = total / Freqquadratcount) %>%
  dplyr::select(lambda) %>%
  pull(lambda)

QCountTable <- Qcount %>%
  mutate(Pr = ((lambda^Var1)*exp(-lambda))/factorial(Var1)) %>%
  mutate(Expected = (round(Pr * sums$Freqquadratcount,0)))

plot(c(1,5),c(0,14), type="n",
xlab="Number of Blue Plaques (Red=Observed,Blue=Expected)", 
     ylab="Frequency of Occurances")
points(QCountTable$Freqquadratcount, 
       col="Red", 
       type="o", 
       lwd=3)
points(QCountTable$Expected, col="Blue", 
       type="o", 
       lwd=3)

teststats <- quadrat.test(BluePlaquesSub.ppp, nx = 6, ny = 6)
plot(BluePlaquesSub.ppp,pch=16,cex=0.5,main="Blue Plaques in Harrow")
plot(teststats,add=T,col="red")

K <- BluePlaquesSub.ppp %>%
  Kest(., correction="border") %>%
  plot()

st_geometry(BoroughMap)

BluePlaquesSubPoints <- BluePlaquesSub %>%
  coordinates(.) %>%
  as.data.frame()

db <- BluePlaquesSubPoints %>%
  fpc::dbscan(.,eps = 700,MinPts = 4)

plot(db, BluePlaquesSubPoints, main = "DBSCAN Output", frame = F)
plot(BoroughMap$geometry,add = T)

BluePlaquesSubPoints %>%
  dbscan::kNNdistplot(.,k=4)

BluePlaquesSubPoints <- BluePlaquesSubPoints %>%
  mutate(dbcluster = db$cluster)

chulls <- BluePlaquesSubPoints %>%
  group_by(dbcluster) %>%
  dplyr::mutate(hull = 1:n(),
               hull = factor(hull,chull(coords.x1,coords.x2))) %>%
  arrange(hull)
这段代码什么意思

chulls <- chulls %>%
  filter(dbcluster >= 1)

dbplot <- ggplot(data = BluePlaquesSubPoints,
                 aes(coords.x1,coords.x2,colour=dbcluster,fill=dbcluster))
dbplot <- dbplot + geom_point()
dbplot <- dbplot + geom_polygon(data = chulls,
                                aes(coords.x1,coords.x2,group=dbcluster),
                                alpha = 0.5)
dbplot + theme_bw() + coord_equal()

HarrowWGSbb <- Harrow %>%
  st_transform(.,4326) %>%
  st_bbox()

basemap <- OpenStreetMap::openmap(c(51.5549876,-0.4040502),c(51.6405356,-0.2671315),
                         zoom=NULL,
                         "stamen-toner")

basemap_bng <- openproj(basemap, projection="+init=epsg:27700")

autoplot.OpenStreetMap(basemap_bng) +
  geom_point(data = BluePlaquesSubPoints,
             aes(coords.x1,coords.x2,
                 colour = dbcluster,
                 fill = dbcluster)) +
  geom_polygon(data = chulls,
               aes(coords.x1,coords.x2,
                   group = dbcluster,
                   fill = dbcluster),
               alpha = 0.5)
```
